Dev th change service to orm
trevorhuis-smoothstack/LMS-Librarian pull request #9
Opened 2020-05-13 19:19 UTC by trevorhuis-smoothstack

Hey Sean, I left the unused functions from the service and controller classes in there if you wanted to make any edits. I know this was under your responsibilities.

2020-05-13 20:59 UTC, justin-obrien-smoothstack requested changes
I think when updating a branch, we should first make sure the branch exists. Similarly when changing the number of copies, we should make sure the book and branch both exist.

Also, a few of the removed methods still seem relevant. We want to be able to get a list of all branches so the user can pick what branch they manage, and a list of all books (or search by title, etc.) so they can choose what book to change the number of copies of. We also want to be able to tell them how many copies of a book their branch currently has.

2020-05-13 20:59 UTC, justin-obrien-smoothstack commented on src/main/java/com/ss/training/lms/controller/LibrarianController.java
>                                                 @RequestBody BookCopies bookCopies)
Something I didn't think of before: What if the bookCopies object has a different branchId or bookId than those given as path parameters? Currently, the path parameters aren't actually used. We could just get rid of them and use a single path for this method, or we could change the request body parameter to just an integer (the new number of copies), or we could even add the number of copies as a new path parameter, though that seems somewhat counter-intuitive.

2020-05-13 20:59 UTC, justin-obrien-smoothstack commented on src/main/java/com/ss/training/lms/controller/LibrarianController.java
>                               @RequestBody LibraryBranch libraryBranch){
Similarly, the branchId in the path for this method isn't used either. The branch that gets updated is always the one with the ID of the one that gets passed in the request body.

2020-05-13 22:02 UTC, sean-darsie approved these changes
We can just leave them for now. It doesn't hurt, and we may want them later to display information to the user in a UI that we build later.

2020-05-14 04:18 UTC, trevorhuis-smoothstack commented
I just pushed with fixes to all concerning comments

2020-05-14 16:17 UTC, merged